# Generated by Django 4.0.4 on 2022-06-03 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_book_id_alter_readinglist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('pie', 'Pie Chart')], max_length=15)),
                ('day', models.IntegerField(default=1)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'Feburary'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021')])),
                ('stateAbr', models.CharField(max_length=2)),
                ('filter_field', models.CharField(choices=[('positive', 'Total Positive Cases to Date'), ('positiveIncrease', 'Daily Increase in Positive Cases'), ('hospittalizedCurrently', 'Currently Hospitalized'), ('onVentilatorCurrently', 'Currently On a Ventilator'), ('death', 'Deaths to Date'), ('deathIncrease', 'Daily Increase in Deaths')], max_length=40)),
                ('user_id', models.ForeignKey(help_text='Testing Functionality', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
