# Generated by Django 4.0.4 on 2022-06-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='user_id',
            new_name='creator_user',
        ),
    ]
