# Generated by Django 4.0.4 on 2022-06-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_id_chart_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='filter_field',
            field=models.CharField(choices=[('positive', 'Total Positive Cases to Date'), ('positiveIncrease', 'Daily Increase in Positive Cases'), ('hospitalizedCurrently', 'Currently Hospitalized'), ('onVentilatorCurrently', 'Currently On a Ventilator'), ('death', 'Deaths to Date'), ('deathIncrease', 'Daily Increase in Deaths')], max_length=40),
        ),
    ]
