# Generated by Django 4.0.4 on 2022-06-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chart_month_alter_chart_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='month',
            field=models.IntegerField(choices=[(0, 'January'), (20, 'Feburary'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='chart',
            name='year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021')]),
        ),
    ]
