# Generated by Django 4.0.4 on 2022-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_chart_month_alter_chart_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'Feburary'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=15),
        ),
    ]
