# Generated by Django 4.0.4 on 2022-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_chart_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021')], max_length=15),
        ),
    ]
