# Generated by Django 4.0.4 on 2022-06-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_chart_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='day',
            field=models.CharField(default='ak', max_length=2),
        ),
    ]
