# Generated by Django 4.0.4 on 2022-06-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chart_plot_entry_alter_chart_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='plot_entry',
            field=models.BinaryField(editable=True),
        ),
    ]
