# Generated by Django 4.0.5 on 2022-07-02 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_chart_plot_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='creator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StatesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_1', models.CharField(max_length=2)),
                ('state_2', models.CharField(max_length=2)),
                ('state_3', models.CharField(max_length=2)),
                ('state_4', models.CharField(max_length=2)),
                ('state_5', models.CharField(max_length=2)),
                ('state_6', models.CharField(max_length=2)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chart')),
            ],
        ),
    ]
