# Generated by Django 4.0.5 on 2022-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_chart_creator_user_stateslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateslist',
            name='state_1',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_2',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_3',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_4',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_5',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_6',
            field=models.CharField(default='', max_length=2),
        ),
    ]
