# Generated by Django 4.0.5 on 2022-07-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_stateslist_state_1_alter_stateslist_state_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateslist',
            name='state_2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_3',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_4',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_5',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='stateslist',
            name='state_6',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
