# Generated by Django 4.0.5 on 2022-07-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_stateslist_state_2_alter_stateslist_state_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stateslist',
            old_name='state_1',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='stateslist',
            name='state_2',
        ),
        migrations.RemoveField(
            model_name='stateslist',
            name='state_3',
        ),
        migrations.RemoveField(
            model_name='stateslist',
            name='state_4',
        ),
        migrations.RemoveField(
            model_name='stateslist',
            name='state_5',
        ),
        migrations.RemoveField(
            model_name='stateslist',
            name='state_6',
        ),
    ]
