# Generated by Django 4.0.5 on 2022-07-03 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_state_1_stateslist_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='day',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='filter_field',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='month',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='stateAbr',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='year',
        ),
        migrations.AddField(
            model_name='chart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.CreateModel(
            name='ChartProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('pie', 'Pie Chart')], max_length=15)),
                ('day', models.CharField(default='01', max_length=2)),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'Feburary'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=15)),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021')], max_length=15)),
                ('stateAbr', models.CharField(max_length=2)),
                ('filter_field', models.CharField(choices=[('positive', 'Total Positive Cases to Date'), ('positiveIncrease', 'Daily Increase in Positive Cases'), ('hospitalizedCurrently', 'Currently Hospitalized'), ('onVentilatorCurrently', 'Currently On a Ventilator'), ('death', 'Deaths to Date'), ('deathIncrease', 'Daily Increase in Deaths')], max_length=40)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chart')),
            ],
        ),
    ]
