# Generated by Django 4.0.5 on 2022-07-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_chart_chart_type_remove_chart_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
