# Generated by Django 4.0.5 on 2022-07-04 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglist',
            name='creator_user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ReadingList',
        ),
    ]
