# Generated by Django 4.0.5 on 2022-07-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_readinglist_creator_user_delete_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateslist',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
