# Generated by Django 4.0.5 on 2022-07-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_stateslist_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateslist',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
    ]
